-- StormSense AI Phase 6.0 Supabase PostgreSQL schema
-- Source: MySQL Workbench export Dump20260607
-- Scope: persistence migration only; forecasting and scientific engines are unchanged.

BEGIN;

CREATE TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(100) NOT NULL DEFAULT 'MET_CHIEF',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS profiles (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    auth_user_id UUID,
    display_name VARCHAR(255),
    station_scope TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit_login (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    email VARCHAR(255),
    status VARCHAR(40) NOT NULL CHECK (status IN ('SUCCESS', 'FAILED', 'LOCKED', 'REVOKED')),
    detail TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS thunderstorm_forecasts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    station VARCHAR(255),
    station_code VARCHAR(255),
    cape DOUBLE PRECISION,
    lifted_index DOUBLE PRECISION,
    sweat_index DOUBLE PRECISION,
    k_index DOUBLE PRECISION,
    pwat DOUBLE PRECISION,
    forecast VARCHAR(255),
    storm_probability INTEGER CHECK (storm_probability IS NULL OR storm_probability BETWEEN 0 AND 100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE thunderstorm_forecasts
    ADD COLUMN IF NOT EXISTS storm_probability INTEGER;

CREATE INDEX IF NOT EXISTS idx_thunderstorm_forecasts_created_at
    ON thunderstorm_forecasts (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_thunderstorm_forecasts_station_created_at
    ON thunderstorm_forecasts (station, created_at DESC);

CREATE TABLE IF NOT EXISTS historical_observations (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    record_date DATE,
    observation_time VARCHAR(40),
    station VARCHAR(255),
    station_code VARCHAR(50),
    observed_event VARCHAR(100),
    source_file TEXT,
    source_sheet TEXT,
    raw_json JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_historical_observations_station_date
    ON historical_observations (station, record_date DESC);

CREATE TABLE IF NOT EXISTS historical_records (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    record_date DATE,
    observation_time VARCHAR(40),
    station VARCHAR(255),
    station_code VARCHAR(50),
    observed_event VARCHAR(100),
    source_file TEXT,
    source_sheet TEXT,
    raw_json JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_historical_records_station_date
    ON historical_records (station, record_date DESC);

CREATE TABLE IF NOT EXISTS thunderstorm_registry (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    record_date DATE,
    observation_time VARCHAR(40),
    station VARCHAR(255),
    station_code VARCHAR(50),
    observed_event VARCHAR(100),
    thunderstorm BOOLEAN DEFAULT FALSE,
    nwx BOOLEAN DEFAULT FALSE,
    severe_storm BOOLEAN DEFAULT FALSE,
    forecast_result VARCHAR(255),
    verification_result VARCHAR(100),
    season VARCHAR(40),
    source_dataset TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_thunderstorm_registry_station_date
    ON thunderstorm_registry (station, record_date DESC);

CREATE INDEX IF NOT EXISTS idx_thunderstorm_registry_event_flags
    ON thunderstorm_registry (thunderstorm, nwx, severe_storm);

CREATE TABLE IF NOT EXISTS verification_results (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    record_date DATE,
    station VARCHAR(255),
    observed_event VARCHAR(100),
    forecast_result VARCHAR(255),
    verification_result VARCHAR(100),
    csi DOUBLE PRECISION,
    hss DOUBLE PRECISION,
    pod DOUBLE PRECISION,
    far DOUBLE PRECISION,
    bias DOUBLE PRECISION,
    source_dataset TEXT,
    raw_json JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS uploaded_datasets (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    file_name TEXT NOT NULL,
    storage_bucket TEXT,
    storage_path TEXT,
    total_records INTEGER DEFAULT 0,
    thunderstorm_records INTEGER DEFAULT 0,
    nwx_records INTEGER DEFAULT 0,
    severe_storm_records INTEGER DEFAULT 0,
    quality_score INTEGER DEFAULT 0 CHECK (quality_score BETWEEN 0 AND 100),
    analysis_json JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS reviewer_dashboard_records (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    reviewer_id TEXT,
    docket_id TEXT,
    station VARCHAR(255),
    record_date DATE,
    verdict VARCHAR(100),
    recommended_action TEXT,
    comments TEXT,
    export_storage_path TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    action VARCHAR(100) NOT NULL,
    status VARCHAR(40) NOT NULL,
    detail TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO roles (name, description)
VALUES ('MET_CHIEF', 'Meteorological operations chief')
ON CONFLICT (name) DO NOTHING;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.schemata WHERE schema_name = 'storage') THEN
        INSERT INTO storage.buckets (id, name, public, file_size_limit)
        VALUES
            ('historical-archives', 'historical-archives', false, 52428800),
            ('uploaded-soundings', 'uploaded-soundings', false, 52428800),
            ('forecast-exports', 'forecast-exports', false, 52428800),
            ('reviewer-dockets', 'reviewer-dockets', false, 52428800),
            ('imd-bulletins', 'imd-bulletins', false, 52428800),
            ('research-documents', 'research-documents', false, 52428800)
        ON CONFLICT (id) DO NOTHING;
    END IF;
END $$;

COMMIT;
