import os
from contextlib import contextmanager
from pathlib import Path
from typing import Any
from urllib.parse import quote_plus


def _find_env_file(start: Path) -> Path | None:
    for directory in (start, *start.parents):
        candidate = directory / ".env"
        if candidate.exists():
            return candidate
    return None


try:
    from dotenv import load_dotenv
except Exception:  # pragma: no cover
    load_dotenv = None

if load_dotenv:
    env_file = _find_env_file(Path(__file__).resolve().parent)
    if env_file:
        load_dotenv(env_file)


try:
    from sqlalchemy import create_engine, text
    from sqlalchemy.engine import Engine
except Exception:  # pragma: no cover - keeps local tooling alive before dependencies are installed
    create_engine = None
    text = None
    Engine = Any


DATABASE_URL = os.getenv("DATABASE_URL", "").strip()


def get_database_url_from_env() -> str:
    if os.getenv("DATABASE_URL", "").strip():
        return os.getenv("DATABASE_URL", "").strip()
    host = os.getenv("SUPABASE_DB_HOST", "").strip()
    password = os.getenv("SUPABASE_DB_PASSWORD", "")
    if not host or not password:
        return ""
    user = os.getenv("SUPABASE_DB_USER", "postgres").strip()
    port = os.getenv("SUPABASE_DB_PORT", "5432").strip()
    name = os.getenv("SUPABASE_DB_NAME", "postgres").strip()
    encoded_password = quote_plus(password)
    return f"postgresql://{user}:{encoded_password}@{host}:{port}/{name}?sslmode=require"


def _normalize_database_url(url: str) -> str:
    if url.startswith("postgres://"):
        return "postgresql+psycopg2://" + url[len("postgres://"):]
    if url.startswith("postgresql://"):
        return "postgresql+psycopg2://" + url[len("postgresql://"):]
    return url


def database_configured() -> bool:
    return bool(get_database_url_from_env() and create_engine and text)


_engine: Engine | None = None


def get_engine() -> Engine | None:
    global _engine
    if _engine is not None:
        return _engine
    if not database_configured():
        return None
    _engine = create_engine(
        _normalize_database_url(get_database_url_from_env()),
        pool_size=int(os.getenv("DB_POOL_SIZE", "10")),
        max_overflow=int(os.getenv("DB_MAX_OVERFLOW", "20")),
        pool_pre_ping=True,
        pool_recycle=int(os.getenv("DB_POOL_RECYCLE_SECONDS", "1800")),
        future=True,
    )
    return _engine


@contextmanager
def db_session():
    engine = get_engine()
    if engine is None:
        yield None
        return
    with engine.begin() as connection:
        yield connection


def fetch_one(query: str, params: dict[str, Any] | None = None) -> dict[str, Any] | None:
    if text is None:
        return None
    with db_session() as connection:
        if connection is None:
            return None
        row = connection.execute(text(query), params or {}).mappings().first()
        return dict(row) if row else None


def fetch_all(query: str, params: dict[str, Any] | None = None) -> list[dict[str, Any]]:
    if text is None:
        return []
    with db_session() as connection:
        if connection is None:
            return []
        rows = connection.execute(text(query), params or {}).mappings().all()
        return [dict(row) for row in rows]


def execute_write(query: str, params: dict[str, Any] | None = None) -> int:
    if text is None:
        return 0
    with db_session() as connection:
        if connection is None:
            return 0
        result = connection.execute(text(query), params or {})
        return int(result.rowcount or 0)


def init_database_schema() -> bool:
    statements = [
        """
        CREATE TABLE IF NOT EXISTS roles (
            id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            name VARCHAR(100) NOT NULL UNIQUE,
            description TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS users (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(255) NOT NULL,
            email VARCHAR(255) NOT NULL UNIQUE,
            password VARCHAR(255) NOT NULL,
            role VARCHAR(100) NOT NULL DEFAULT 'MET_CHIEF',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS profiles (
            id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
            display_name VARCHAR(255),
            station_scope TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS audit_login (
            id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
            email VARCHAR(255),
            status VARCHAR(40) NOT NULL,
            detail TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS thunderstorm_forecasts (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            station VARCHAR(255),
            station_code VARCHAR(255),
            cape DOUBLE PRECISION,
            lifted_index DOUBLE PRECISION,
            sweat_index DOUBLE PRECISION,
            k_index DOUBLE PRECISION,
            pwat DOUBLE PRECISION,
            forecast VARCHAR(255),
            storm_probability INTEGER,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """,
        "ALTER TABLE thunderstorm_forecasts ADD COLUMN IF NOT EXISTS storm_probability INTEGER",
        "CREATE INDEX IF NOT EXISTS idx_thunderstorm_forecasts_created_at ON thunderstorm_forecasts (created_at DESC)",
        "CREATE INDEX IF NOT EXISTS idx_thunderstorm_forecasts_station_created_at ON thunderstorm_forecasts (station, created_at DESC)",
        """
        CREATE TABLE IF NOT EXISTS historical_observations (
            id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            record_date DATE,
            observation_time VARCHAR(40),
            station VARCHAR(255),
            station_code VARCHAR(50),
            observed_event VARCHAR(100),
            source_file TEXT,
            source_sheet TEXT,
            raw_json JSONB,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """,
        "CREATE INDEX IF NOT EXISTS idx_historical_observations_station_date ON historical_observations (station, record_date DESC)",
        """
        CREATE TABLE IF NOT EXISTS historical_records (
            id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            record_date DATE,
            observation_time VARCHAR(40),
            station VARCHAR(255),
            station_code VARCHAR(50),
            observed_event VARCHAR(100),
            source_file TEXT,
            source_sheet TEXT,
            raw_json JSONB,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """,
        "CREATE INDEX IF NOT EXISTS idx_historical_records_station_date ON historical_records (station, record_date DESC)",
        """
        CREATE TABLE IF NOT EXISTS thunderstorm_registry (
            id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            record_date DATE,
            observation_time VARCHAR(40),
            station VARCHAR(255),
            station_code VARCHAR(50),
            observed_event VARCHAR(100),
            thunderstorm BOOLEAN DEFAULT FALSE,
            nwx BOOLEAN DEFAULT FALSE,
            severe_storm BOOLEAN DEFAULT FALSE,
            forecast_result VARCHAR(255),
            verification_result VARCHAR(100),
            season VARCHAR(40),
            source_dataset TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """,
        "CREATE INDEX IF NOT EXISTS idx_thunderstorm_registry_station_date ON thunderstorm_registry (station, record_date DESC)",
        "CREATE INDEX IF NOT EXISTS idx_thunderstorm_registry_event_flags ON thunderstorm_registry (thunderstorm, nwx, severe_storm)",
        """
        CREATE TABLE IF NOT EXISTS verification_results (
            id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            record_date DATE,
            station VARCHAR(255),
            observed_event VARCHAR(100),
            forecast_result VARCHAR(255),
            verification_result VARCHAR(100),
            csi DOUBLE PRECISION,
            hss DOUBLE PRECISION,
            pod DOUBLE PRECISION,
            far DOUBLE PRECISION,
            bias DOUBLE PRECISION,
            source_dataset TEXT,
            raw_json JSONB,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS uploaded_datasets (
            id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            file_name TEXT NOT NULL,
            storage_bucket TEXT,
            storage_path TEXT,
            total_records INTEGER DEFAULT 0,
            thunderstorm_records INTEGER DEFAULT 0,
            nwx_records INTEGER DEFAULT 0,
            severe_storm_records INTEGER DEFAULT 0,
            quality_score INTEGER DEFAULT 0,
            analysis_json JSONB,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """,
        "ALTER TABLE uploaded_datasets ADD COLUMN IF NOT EXISTS nwx_records INTEGER DEFAULT 0",
        "ALTER TABLE uploaded_datasets ADD COLUMN IF NOT EXISTS severe_storm_records INTEGER DEFAULT 0",
        """
        CREATE TABLE IF NOT EXISTS reviewer_dashboard_records (
            id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            reviewer_id TEXT,
            docket_id TEXT,
            station VARCHAR(255),
            record_date DATE,
            verdict VARCHAR(100),
            recommended_action TEXT,
            comments TEXT,
            export_storage_path TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS audit_logs (
            id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            action VARCHAR(100) NOT NULL,
            status VARCHAR(40) NOT NULL,
            detail TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """,
    ]
    engine = get_engine()
    if engine is None or text is None:
        return False
    with engine.begin() as connection:
        for statement in statements:
            connection.execute(text(statement))
        connection.execute(
            text("INSERT INTO roles (name, description) VALUES (:name, :description) ON CONFLICT (name) DO NOTHING"),
            {"name": "MET_CHIEF", "description": "Meteorological operations chief"},
        )
    return True


def database_status() -> str:
    try:
        row = fetch_one("SELECT 1 AS ok")
        return "CONNECTED" if row and row.get("ok") == 1 else "UNCONFIGURED"
    except Exception:
        return "OFFLINE"
